cp  figs/Fig1a_higherSC.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig1b_higherNSC.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig2_pt_SC_NSC.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig4_ModelComparison_EKRT.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig5_ModelComparison_VISH.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig6_ModelComparison_AMPT.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig7_chisqndf_bestfits_3pad.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig8_pt_NSC32_Models.eps ~/GitHub/paperQConly/figs/
cp  figs/Fig9_pt_NSC42_Models.eps ~/GitHub/paperQConly/figs/
